#!/usr/bin/env bash
# Install the commit-msg hook that runs Tools/check-commit.sh.
#
#     Tools/install-hooks.sh              # install, or refresh an existing one
#     Tools/install-hooks.sh --status     # is it installed?
#     Tools/install-hooks.sh --uninstall  # remove it again
#
# Why the hook is generated instead of being a file in .git/hooks:
#
#   * .git/hooks is not in version control. A hook written there exists on one
#     machine, survives no clone, and shows up in no diff — the part that could
#     be reviewed would be invisible, and the part that is visible (this script)
#     would not be the thing actually running. So the rules stay in
#     Tools/check-commit.sh plus docs/commits.md, and this script only wires
#     them into git.
#   * The shim is written to `.cache/hooks/`, which .gitignore already covers
#     (same family as Tools/bin/), and the repo-local `core.hooksPath` points
#     there. A relative core.hooksPath is resolved against the worktree root, so
#     it is found when committing from a subdirectory, and it keeps working if
#     the checkout moves.
#   * The shim finds its repository with `git rev-parse --show-toplevel` instead
#     of baking in an absolute path, so nothing machine-specific is written into
#     .git/config.
#
# Safety: someone else's `core.hooksPath` is never clobbered — not by install,
# not by --uninstall, which only removes a shim carrying this script's marker.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(dirname "$HERE")"
CHECK="$HERE/check-commit.sh"

SHIM_DIR=".cache/hooks"          # relative to the worktree root, gitignored
SHIM="$SHIM_DIR/commit-msg"
MARK="Generated by Tools/install-hooks.sh"

usage() {
	cat <<'EOF'
用法：install-hooks.sh [--status | --uninstall]

  不带参数      安装或刷新 commit-msg 钩子（每个 clone 装一次）
  --status      看装没装；装好了退出 0，没装退出 1
  --uninstall   卸载：恢复 core.hooksPath 并删掉生成的 shim
  -h, --help    显示这份帮助

它做的事只有两件：把一段两行的 shim 写到 .cache/hooks/commit-msg（.gitignore
已经忽略 .cache/），再把仓库本地的 core.hooksPath 指过去。**不写 .git/hooks/** ——
那个目录不进版本控制，钩子放进去就没人知道它从哪来、改了什么都看不见。

装了之后，`git commit` 会先跑 Tools/check-commit.sh 检查提交信息；确实要绕过时
用 `git commit --no-verify`，但先确认不是消息写错了。规范见 docs/commits.md。
EOF
}

fail() { # $1 = headline, rest = detail
	printf '!! %s\n' "$1" >&2
	shift
	while [[ $# -gt 0 ]]; do
		printf '   %s\n' "$1" >&2
		shift
	done
	exit 2
}

toplevel() {
	local top
	top="$(git rev-parse --show-toplevel 2>/dev/null || true)"
	if [[ -z "$top" ]]; then
		fail "这里不是 git 仓库（或 git 不可用）。" \
			"这是个 per-repo 的钩子，请在 clone 出来的仓库里运行。"
	fi
	printf '%s' "$top"
}

shim_body() {
	cat <<EOF
#!/bin/sh
# $MARK — do not edit; rerun the installer.
exec "\$(git rev-parse --show-toplevel)/Tools/check-commit.sh" "\$1"
EOF
}

current_hookspath() {
	git -C "$1" config --get core.hooksPath 2>/dev/null || true
}

shim_looks_like_ours() {
	[[ -f "$1" ]] && grep -qF "$MARK" "$1"
}

# --status asks a stronger question than "did this script ever run here": the
# shim has to be the one this script would write now. A shim that still carries
# the marker but points somewhere else (hand-edited, or written by an older
# layout) would otherwise be reported as installed while every commit in the
# repository fails inside it.
shim_matches() {
	[[ -f "$1" ]] || return 1
	[[ "$(cat "$1")" == "$(shim_body)" ]]
}

MODE=install
case "${1:-}" in
	'') ;;
	--status) MODE=status ;;
	--uninstall) MODE=uninstall ;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		printf '!! 不认识的参数：%s\n\n' "$1" >&2
		usage >&2
		exit 2
		;;
esac
[[ $# -le 1 ]] || fail "参数太多了：$*"

TOP="$(toplevel)"
HOOKS_PATH="$(current_hookspath "$TOP")"
SHIM_ABS="$TOP/$SHIM"

case "$MODE" in
status)
	problems=()
	[[ "$HOOKS_PATH" == "$SHIM_DIR" ]] || problems+=("core.hooksPath 是 [${HOOKS_PATH:-未设置}]，不是 [$SHIM_DIR]")
	if ! shim_matches "$SHIM_ABS"; then
		if shim_looks_like_ours "$SHIM_ABS"; then
			problems+=("$SHIM 的内容和这个脚本现在会生成的 shim 不一致（被手改过？）")
		else
			problems+=("$SHIM 不存在，或者不是这个脚本生成的")
		fi
	fi
	if [[ ${#problems[@]} -eq 0 ]]; then
		printf '✓ 钩子已装且内容正确：%s → Tools/check-commit.sh\n' "$SHIM"
		exit 0
	fi
	# One line either way, so --status stays usable from a script or a prompt.
	joined="$(printf '%s；' "${problems[@]}")"
	printf '✗ 钩子没装好：%s（重新装上：Tools/install-hooks.sh）\n' "${joined%；}" >&2
	exit 1
	;;
uninstall)
	if [[ -z "$HOOKS_PATH" ]]; then
		printf '✓ 本来就没装（core.hooksPath 未设置），不用卸载。\n'
		exit 0
	fi
	if [[ "$HOOKS_PATH" != "$SHIM_DIR" ]]; then
		fail "core.hooksPath 指向 [$HOOKS_PATH]，不是本脚本装的，不动它。" \
			"要卸载自己装的东西，请手动 git config --unset core.hooksPath。"
	fi
	git -C "$TOP" config --unset core.hooksPath
	# The shim can only have been written by this script; still, only delete a
	# file that carries the marker, so a hand-written commit-msg is never lost.
	if shim_looks_like_ours "$SHIM_ABS"; then
		rm -f "$SHIM_ABS"
		rmdir "$TOP/$SHIM_DIR" 2>/dev/null || true
	fi
	printf '✓ 已卸载：core.hooksPath 恢复，%s 删掉。\n' "$SHIM"
	printf '  现在 commit 不再检查提交信息了。\n'
	;;
install)
	if [[ ! -f "$CHECK" || ! -x "$CHECK" ]]; then
		fail "找不到可执行的 ${CHECK}。" \
			"钩子只是它的外壳：装之前 Tools/check-commit.sh 得先能跑（chmod +x）。"
	fi
	if [[ -n "$HOOKS_PATH" && "$HOOKS_PATH" != "$SHIM_DIR" ]]; then
		fail "core.hooksPath 已经指向 [$HOOKS_PATH]，看起来是别的工具装的，不覆盖它。" \
			"要么继续用它，要么先 git config --unset core.hooksPath 再装这个。"
	fi

	mkdir -p "$TOP/$SHIM_DIR"
	shim_body >"$SHIM_ABS"
	chmod +x "$SHIM_ABS"
	git -C "$TOP" config core.hooksPath "$SHIM_DIR"

	printf '✓ 钩子已装：core.hooksPath → %s\n' "$SHIM_DIR"
	printf '  %s → Tools/check-commit.sh\n' "$SHIM"
	# A hook directory the tree does not ignore would show up as an untracked
	# change for everybody who runs this; say so instead of surprising them.
	if ! git -C "$TOP" check-ignore -q "$SHIM_DIR/commit-msg"; then
		printf '!! 注意：%s 没被 .gitignore 忽略，git status 会多出一项。\n' "$SHIM_DIR/"
	fi
	printf '  现在提交信息会被检查（规范见 docs/commits.md）；确要绕过用 git commit --no-verify。\n'
	;;
esac
