// Generated by Tools/make-claude-schema.py from the upstream settings
// reference. Do not edit by hand; re-run the script after an upgrade.
//
// Labels are the literal JSON keys — the key identifies the setting in
// ~/.claude/settings.json, so naming it in Chinese would hide which key is
// being edited. They are written as a zh/en pair rather than a plain string
// so that no shipped schema carries a value in one language only.

import Foundation

extension SettingsSchema {
	public static let claudeCode = SettingsSchemaDefinition(
		id: "claude-code",
		title: .both(zh: "Claude Code 设置", en: "Claude Code settings"),
		sections: [
			SettingsSection(
				id: "claude-model-and-responses",
				title: .both(zh: "模型与回复", en: "Model and responses"),
				icon: "cpu",
				fields: [
					textField(
						"advisorModel", .both(zh: "advisorModel", en: "advisorModel"), "",
						.both(zh: "选择 Claude 调用服务端 advisor 工具时由哪个模型作答。不设置则关闭 advisor。advisor 的能力必须不低于主模型。可接受的模型组合，以及选了不被接受的模型会怎样，见「选择一个 advisor 模型」。", en: "Pick which model answers when Claude calls the server-side advisor tool. Unset it to turn the advisor off. The advisor must be at least as capable as your main model. See Choose an advisor model for the accepted pairings and what happens when you pick one that isn't accepted…")
					),
					boolField(
						"alwaysThinkingEnabled", .both(zh: "alwaysThinkingEnabled", en: "alwaysThinkingEnabled"), fallback: false,
						.both(zh: "把它设为 false 可以为每个 session 关闭扩展思考。思考默认开启，所以 true 不改变任何行为。多数人通过 /config 设置它，而不是直接编辑文件。在始终思考的模型上，例如 Opus 5.5、Sonnet 5.5 和 Fable 系列，false…", en: "Turn extended thinking off for every session by setting this to false. Thinking is on by default, so true changes nothing. Most people set this through /config rather than by editing the file. On models that always think, such as Opus 5.5, Sonnet 5.5, and the Fable models, false…")
					),
					listField(
						"availableModels", .both(zh: "availableModels", en: "availableModels"),
						.both(zh: "限制人们可以为主 session、subagent、skills 和 advisor 选择哪些模型。组织下发的列表会约束 /model、--model 以及开发者自己文件里的 model 键；不在列表内的模型无法被选中。按默认的前缀匹配，它不会触及…", en: "Restrict which models people can select for the main session, subagents, skills, and the advisor. A managed list constrains /model, --model, and the model key in a developer's own files; a model outside it can't be selected. With the default prefix matching, this doesn't touch…")
					),
					textField(
						"effortLevel", .both(zh: "effortLevel", en: "effortLevel"), "",
						.both(zh: "为还没有保存过等级的模型设置默认 effort 等级。较低等级在简单任务上更快更便宜，较高等级在复杂问题上推理更深。当你在本机的交互式 session 里运行 /effort low、medium、high 或 xhigh 时…", en: "Set a default effort level for models you haven't saved a level for. Lower levels are faster and cheaper on straightforward tasks, and higher levels reason more deeply on complex problems. When you run /effort low, medium, high, or xhigh in an interactive session on your…")
					),
					boolField(
						"enforceAvailableModels", .both(zh: "enforceAvailableModels", en: "enforceAvailableModels"), fallback: false,
						.both(zh: "/model 选择器有一个 **Default** 选项，默认模型设置描述了它解析到哪个模型。availableModels 允许列表限制了你能指定的模型，但在默认的前缀匹配下它不会重映射你账号类型的默认模型，所以 **Default** 仍可能…", en: "The /model picker has a **Default** option, and default model setting describes the model it resolves to. An availableModels allowlist limits the models you can name, but with the default prefix matching it doesn't remap your account type's default, so **Default** can still…")
					),
					listField(
						"fallbackModel", .both(zh: "fallbackModel", en: "fallbackModel"),
						.both(zh: "按顺序指定主模型过载或不可用时 Claude Code 可以尝试的备用模型。Claude Code 会在本轮剩余时间里切到链上的下一个可用模型并给出提示。没有配置链时，Claude Code 用同一个模型重试，然后…", en: "Name backup models for Claude Code to try, in order, when your primary model is overloaded or unavailable. Claude Code switches to the next available model in the chain for the rest of the turn and shows a notice. Without a chain, Claude Code retries the same model and then…")
					),
					boolField(
						"fastMode", .both(zh: "fastMode", en: "fastMode"), fallback: false,
						.both(zh: "在支持的 session 上开启快速模式，用于快速迭代、实时调试这类你要速度、愿意付更高每 token 成本的交互工作。通常不必手动改这个键：运行 /fast 会把 fastMode: true 写入 ~/.claude/settings.json，而运行…", en: "Turn fast mode on for sessions where it's available, for interactive work like rapid iteration or live debugging where you want speed at a higher cost per token. You don't usually edit this key by hand: running /fast writes fastMode: true to ~/.claude/settings.json, and running…")
					),
					boolField(
						"fastModePerSessionOptIn", .both(zh: "fastModePerSessionOptIn", en: "fastModePerSessionOptIn"), fallback: false,
						.both(zh: "通常运行 /fast 会把 fastMode 保存到用户设置里，于是之后每个 session 启动时快速模式都是开的。把这个键设为 true 可以阻止这种行为：已保存的 fastMode: true 不再在 session 启动时开启快速模式，每个人都要在每个 session 里运行 /fast…", en: "Normally, running /fast saves fastMode to a person's user settings, so fast mode is on at the start of every later session. Set this key to true to stop that: a saved fastMode: true no longer turns fast mode on at session start, and each person has to run /fast in each session…")
					),
					textField(
						"language", .both(zh: "language", en: "language"), "",
						.both(zh: "让 Claude 默认用英语之外的语言回答。回答语言没有固定列表：Claude Code 会把取值原样作为「始终用该语言回答」的指令传给 Claude，所以任何 Claude 能读懂的语言名都可用。Claude Code 不检查…", en: "Have Claude respond in a language other than English by default. There is no fixed list for responses: Claude Code passes the value verbatim to Claude as an instruction to always respond in that language, so any language name Claude can read works. Claude Code doesn't check the…")
					),
					textField(
						"maxEffortLevel", .both(zh: "maxEffortLevel", en: "maxEffortLevel"), "",
						.both(zh: "限制一个 session 可以使用的 effort 等级上限，更低的等级仍然可用。任何更高的等级都会按上限执行，包括来自 /effort、/model 选择器、--effort、CLAUDE_CODE_EFFORT_LEVEL、skill 或 subagent 的 effort frontmatter，以及模型自身默认值的等级。Claude…", en: "Cap the effort level a session can use, leaving lower levels available. Any higher level runs at the cap instead, including one from /effort, the /model picker, --effort, CLAUDE_CODE_EFFORT_LEVEL, a skill's or subagent's effort frontmatter, or the model's own default. Claude…")
					),
					textField(
						"model", .both(zh: "model", en: "model"), "",
						.both(zh: "设置每个新 session 使用的模型，这样就不必每次都用 /model 挑一个。在这里设置并不妨碍你在 session 中途切换。如果管理员设置了组织默认模型来覆盖用户选择，那么即使你在这个键里设置了别的模型，你得到的仍是那个模型…", en: "Set the model every new session uses, so you don't have to pick one with /model each time. Setting it here doesn't stop you from switching mid-session. If your admin set an organization default model to override user selection, you get that model even when you set this key in…")
					),
					jsonField(
						"modelOverrides", .both(zh: "modelOverrides", en: "modelOverrides"),
						.both(zh: "把 Anthropic 模型 ID 映射到 provider 特定的模型 ID，例如 Amazon Bedrock 推理配置文件 ARN。此后每个模型选择器条目在调用 provider API 时都会使用映射后的值。管理员在 Amazon Bedrock、Google Cloud 的 Agent Platform 和 Microsoft…", en: "Map Anthropic model IDs to provider-specific model IDs, such as Amazon Bedrock inference profile ARNs. Each model picker entry then uses its mapped value when calling the provider API. Administrators use this on Amazon Bedrock, Google Cloud's Agent Platform, and Microsoft…")
					),
					listField(
						"modelPicker", .both(zh: "modelPicker", en: "modelPicker"),
						.both(zh: "列出 /model 选择器提供的模型，顺序按你写的来，标签由你决定，让选择器在内置阵容之后、或替代内置阵容，列出你的组织实际运行的模型。每一行的模型都按原样使用，因此它接受 --model 接受的一切：一个…", en: "List the models the /model picker offers, in the order you write them and under labels you choose, so the picker lists the models your organization runs, after the built-in lineup or instead of it. Each row's model is taken verbatim, so it accepts anything --model accepts: an…")
					),
					jsonField(
						"modelSettings", .both(zh: "modelSettings", en: "modelSettings"),
						.both(zh: "为你使用的每个模型保存 effort 等级。需要 Claude Code v2.1.251 或更高版本。在你机器上的交互式 session 里，当你用 /effort 或 /model 选择器的 effort 滑杆把 low、medium、high 或 xhigh 保存为默认时，Claude Code 会把该等级写到这里…", en: "Save an effort level for each model you use. Requires Claude Code v2.1.251 or later. In an interactive session on your machine, when you save low, medium, high, or xhigh as your default with /effort or the /model picker's effort slider, Claude Code writes that level here under…")
					),
					textField(
						"outputStyle", .both(zh: "outputStyle", en: "outputStyle"), "",
						.both(zh: "按名称选择输出风格。输出风格是一组保存下来的指令，会改变 Claude 的角色、语气和输出格式，例如内置的 Explanatory 和 Learning 风格，或者你自己写的风格。如果你在 session 中途改这个键，Claude 会立即用新风格…", en: "Select an output style by name. An output style is a saved set of instructions that changes Claude's role, tone, and output format, such as the built-in Explanatory and Learning styles or one you wrote yourself. If you change this key during a session, Claude uses the new style…")
					),
					textField(
						"promptCacheTtl", .both(zh: "promptCacheTtl", en: "promptCacheTtl"), "",
						.both(zh: "选择 prompt 缓存为主对话保留多久。这个键适用于你的交互式、-p 和 Agent SDK 轮次，以及 Claude Code 与它们内联运行的辅助请求。一小时的生命周期能让缓存在较长中断后仍然温热，API 会为每次缓存…", en: "Choose how long the prompt cache holds the main conversation. This key applies to your interactive, -p, and Agent SDK turns, together with the helpers Claude Code runs inline with them. The one-hour lifetime keeps the cache warm across longer breaks, and the API bills each cache…")
					),
					boolField(
						"showThinkingSummaries", .both(zh: "showThinkingSummaries", en: "showThinkingSummaries"), fallback: false,
						.both(zh: "在交互式 session 中查看 Claude 扩展思考的摘要。如果你希望用 Ctrl+O 展开思考时看到完整摘要，就设置它。未设置或为 false 时，Anthropic API 会隐去思考块，Claude Code 显示一个折叠的占位；第三方 provider 不会…", en: "See summaries of Claude's extended thinking in interactive sessions. Set it if you want the full summaries when you expand thinking with Ctrl+O. When unset or false, the Anthropic API redacts thinking blocks and Claude Code shows a collapsed stub; third-party providers don't…")
					),
					textField(
						"subagentPromptCacheTtl", .both(zh: "subagentPromptCacheTtl", en: "subagentPromptCacheTtl"), "",
						.both(zh: "选择 prompt 缓存为主对话之外、Claude Code 发起的请求保留多久。这个键适用于 subagent、workflow，以及 Claude Code 自己的后台与辅助请求，例如压缩和 session 标题。一小时的生命周期能让缓存保持温热…", en: "Choose how long the prompt cache holds the requests Claude Code makes outside the main conversation. This key applies to subagents, workflows, and Claude Code's own background and helper requests, such as compaction and session titles. The one-hour lifetime keeps the cache warm…")
					),
					boolField(
						"switchModelsOnFlag", .both(zh: "switchModelsOnFlag", en: "switchModelsOnFlag"), fallback: true,
						.both(zh: "选择安全分类器标记某个请求之后会发生什么：切换到 fallback 模型继续，还是暂停下来，让你在切换与修改 prompt 之间选择。", en: "Choose what happens when a safety classifier flags a request: switch to the fallback model and continue, or pause so you can choose between switching and editing the prompt.")
					),
					boolField(
						"ultracode", .both(zh: "ultracode", en: "ultracode"), fallback: false,
						.both(zh: "让 session 启动时开启 ultracode。开启后，Claude 会为每个实质性任务规划一个 workflow，而不是等你去要求。只有在为你启用了动态 workflow、且你的模型支持 xhigh effort 时，Claude 才会规划 workflow。这个键不改变 session 的…", en: "Start sessions with ultracode on. With it on, Claude plans a workflow for each substantive task instead of waiting for you to ask. Claude plans workflows only when dynamic workflows are enabled for you and your model supports xhigh effort. The key doesn't change the session's…")
					),
				]
			),
			SettingsSection(
				id: "claude-permission-settings",
				title: .both(zh: "权限", en: "Permissions"),
				icon: "lock.shield",
				fields: [
					jsonField(
						"autoMode", .both(zh: "autoMode", en: "autoMode"),
						.both(zh: "为 auto mode 分类器拦截和放行的内容添加你自己的规则。用它告诉分类器你的组织信任哪些仓库、bucket 和域名，从而不再拦截常规的内部操作。分类器自带内置的允许与拒绝规则。包含…", en: "Add your own rules to what the auto mode classifier blocks and allows. Use it to tell the classifier which repos, buckets, and domains your organization trusts, so it stops blocking routine internal operations. The classifier ships with built-in allow and deny rules. Include the…")
					),
					boolField(
						"autoMode.classifyAllShell", .both(zh: "autoMode.classifyAllShell", en: "autoMode.classifyAllShell"), fallback: false,
						.both(zh: "在 auto mode 生效期间，让每条 Bash 和 PowerShell 命令都经过 auto mode 分类器。默认情况下，auto mode 只暂停那些可能执行任意代码的允许规则：例如 Bash(*) 这类工具级和通配规则，以及解释器或 shell 包装前缀…", en: "Send every Bash and PowerShell command through the auto mode classifier while auto mode is active. By default, auto mode suspends only allow rules that could run arbitrary code: tool-wide and wildcard rules such as Bash(*), and interpreter or shell-wrapper prefixes such as…")
					),
					textField(
						"disableAutoMode", .both(zh: "disableAutoMode", en: "disableAutoMode"), "",
						.both(zh: "把 auto mode 从 Shift+Tab 循环里移除。任何本来会以 auto mode 启动的 session——无论来自 --permission-mode auto、设置文件还是内置默认值——都会改为以 default 启动。管理员在 managed settings 里设置它，防止其组织里的开发者…", en: "Remove auto mode from the Shift+Tab cycle. Any session that would otherwise start in auto mode, whether from --permission-mode auto, a settings file, or the built-in default, starts in default instead. Administrators set it in managed settings to prevent developers in their…")
					),
					jsonField(
						"permissions", .both(zh: "permissions", en: "permissions"),
						.both(zh: "控制哪些工具 Claude 不用询问就能使用、哪些总是先提示、哪些被禁止，并设置 session 启动时的权限模式。下面每个 permissions.* 键都嵌套在这个对象里。", en: "Control which tools Claude can use without asking, which ones always prompt, and which ones are blocked, and set the permission mode a session starts in. Every permissions.* key below nests under this object.")
					),
					listField(
						"permissions.additionalDirectories", .both(zh: "permissions.additionalDirectories", en: "permissions.additionalDirectories"),
						.both(zh: "让 Claude 可以访问你启动目录之外的目录，作为额外的工作目录。大多数 .claude/ 配置不会从这些目录里被发现。", en: "Give Claude file access to directories outside the one you started in, as additional working directories. Most .claude/ configuration is not discovered from these directories.")
					),
					listField(
						"permissions.allow", .both(zh: "permissions.allow", en: "permissions.allow"),
						.both(zh: "列出 Claude Code 不经询问就批准的工具调用。在 MCP 规则里，* 只能出现在 mcp__<server>__ 前缀之后的工具名中，例如 mcp__github__get_*，不能出现在 server 名里。", en: "List the tool uses Claude Code approves without asking you. In an MCP rule, * can appear only in the tool name after the mcp__<server>__ prefix, such as mcp__github__get_*; it can't appear in the server name.")
					),
					listField(
						"permissions.ask", .both(zh: "permissions.ask", en: "permissions.ask"),
						.both(zh: "列出即使处于本来会直接批准的权限模式（例如 acceptEdits 或 bypassPermissions）也要向你确认的工具调用。在 dontAsk 模式下，Claude Code 会拒绝匹配的工具调用，而不是提示你。", en: "List the tool uses that prompt you for confirmation even in a permission mode that would otherwise approve them, such as acceptEdits or bypassPermissions. In dontAsk mode Claude Code denies a matching tool use instead of prompting.")
					),
					boolField(
						"permissions.blockReadsOutsideWorkingDirectories", .both(zh: "permissions.blockReadsOutsideWorkingDirectories", en: "permissions.blockReadsOutsideWorkingDirectories"), fallback: false,
						.both(zh: "阻止 Claude 用 Read、Grep、Glob 和 LSP 工具读取 session 工作目录之外的路径，在所有权限模式下都生效，包括 bypassPermissions。通过 Claude Code 能识别的文件命令（例如 cat）读取匹配路径的 Bash 命令会提示…", en: "Stop Claude from reading paths outside the session's working directories with the Read, Grep, Glob, and LSP tools, in every permission mode including bypassPermissions. A Bash command that reads a matching path through a file command Claude Code recognizes, such as cat, prompts…")
					),
					textField(
						"permissions.defaultMode", .both(zh: "permissions.defaultMode", en: "permissions.defaultMode"), "",
						.both(zh: "设置新 session 启动时使用的权限模式。不设置时，session 以你所处界面的内置默认模式启动。", en: "Set the permission mode new sessions start in. When you leave it unset, sessions start in the built-in default for your surface.")
					),
					listField(
						"permissions.deny", .both(zh: "permissions.deny", en: "permissions.deny"),
						.both(zh: "列出 Claude Code 禁止的工具调用。用它保护存放 API key、密钥或环境变量值的文件：Claude Code 会把匹配的文件排除在文件发现和搜索结果之外，拒绝读取它们，并阻止对匹配路径使用 Edit 和 Write 工具。Read 和 Edit…", en: "List the tool uses Claude Code blocks. Use it for files that hold API keys, secrets, or environment values: Claude Code excludes matching files from file discovery and search results, denies reads of them, and blocks the Edit and Write tools on the matching paths. Read and Edit…")
					),
					textField(
						"permissions.disableBypassPermissionsMode", .both(zh: "permissions.disableBypassPermissionsMode", en: "permissions.disableBypassPermissionsMode"), "",
						.both(zh: "阻止任何人进入 bypassPermissions 模式。Claude Code 随后会拒绝 --dangerously-skip-permissions 标志，并忽略 agent 定义里的 permissionMode: bypassPermissions，于是 subagent 按父 session 的权限模式运行。", en: "Prevent anyone from entering bypassPermissions mode. Claude Code then rejects the --dangerously-skip-permissions flag, and ignores an agent definition's permissionMode: bypassPermissions, so the subagent runs with the parent session's permission mode.")
					),
					boolField(
						"skipAutoPermissionPrompt", .both(zh: "skipAutoPermissionPrompt", en: "skipAutoPermissionPrompt"), fallback: false,
						.both(zh: "跳过 Claude Code 在你第一次自己进入 auto mode 时显示的那条一次性说明——例如通过你自己的设置或模式选择器进入，而不是由内置默认值让 session 以它启动。Claude Code 只显示该说明一次，然后…", en: "Skip the one-time notice describing auto mode that Claude Code shows when you first enter auto mode yourself, for example through your own settings or the mode selector, rather than when the built-in default starts a session in it. Claude Code shows that notice once and then…")
					),
					boolField(
						"skipDangerousModePermissionPrompt", .both(zh: "skipDangerousModePermissionPrompt", en: "skipDangerousModePermissionPrompt"), fallback: false,
						.both(zh: "跳过 Claude Code 在 session 进入 bypassPermissions 模式之前显示的确认对话框，无论来源是 --dangerously-skip-permissions 还是 defaultMode: 'bypassPermissions'。你接受过一次该对话框后，Claude Code 会在你的用户设置里把这里写成 true。", en: "Skip the confirmation dialog Claude Code shows before a session enters bypassPermissions mode, whether from --dangerously-skip-permissions or from defaultMode: 'bypassPermissions'. Claude Code writes true here in your user settings when you accept that dialog once.")
					),
					boolField(
						"useAutoModeDuringPlan", .both(zh: "useAutoModeDuringPlan", en: "useAutoModeDuringPlan"), fallback: true,
						.both(zh: "选择 Claude Code 是否用 auto mode 分类器审查计划模式下的 shell 命令。默认为 true 时，只要 auto mode 可用，分类器就会在规划期间审查每条命令，你不会看到提示，关键路径上的删除除外。设为 false 会得到…", en: "Choose whether Claude Code uses the auto mode classifier to review shell commands in plan mode. With the default true, the classifier reviews each command during planning when auto mode is available and you see no prompt, except for critical-path removals. Set false to get a…")
					),
				]
			),
			SettingsSection(
				id: "claude-agents-sessions-and-worktrees",
				title: .both(zh: "Agent 与会话", en: "Agents, sessions, and worktrees"),
				icon: "person.2",
				fields: [
					textField(
						"agent", .both(zh: "agent", en: "agent"), "",
						.both(zh: "把主线程作为指定的 subagent 运行，这样 Claude Code 会把该 subagent 的系统 prompt、工具限制和模型应用到你的 session。同一个键也为从 claude agents 派发的 session 设置默认 agent。", en: "Run the main thread as a named subagent, so Claude Code applies that subagent's system prompt, tool restrictions, and model to your session. The same key sets the default agent for sessions you dispatch from claude agents.")
					),
					textField(
						"crossSessionInbound", .both(zh: "crossSessionInbound", en: "crossSessionInbound"), "",
						.both(zh: "选择这个 session 如何处理来自你其它 Claude Code session 的消息。没有适用取值时，Claude Code 会按两个 session 的权限模式类别逐条判断。需要 Claude Code v2.1.224 或更高版本。", en: "Choose what this session does with messages arriving from your other Claude Code sessions. When no value applies, Claude Code decides per message from the two sessions' permission-mode classes. Requires Claude Code v2.1.224 or later.")
					),
					boolField(
						"disableAgentView", .both(zh: "disableAgentView", en: "disableAgentView"), fallback: false,
						.both(zh: "关闭后台 agent 和 agent 视图：claude agents、--bg、/background 以及按需 supervisor。在 managed settings 里设置它，可为整个组织强制生效。", en: "Turn off background agents and agent view: claude agents, --bg, /background, and the on-demand supervisor. Set it in managed settings to enforce it for an organization.")
					),
					boolField(
						"isolatePeerMachines", .both(zh: "isolatePeerMachines", en: "isolatePeerMachines"), fallback: false,
						.both(zh: "在 Claude 的 SendMessage 触达你这台机器之外的某个 session 之前，要求你明确批准；见「跨机器消息需要批准」。即使处于 bypassPermissions 模式也会出现批准提示。", en: "Require your explicit approval before Claude's SendMessage reaches one of your sessions beyond this machine; see Require approval for cross-machine messages. The approval prompt appears even in bypassPermissions mode.")
					),
					textField(
						"processWrapper", .both(zh: "processWrapper", en: "processWrapper"), "",
						.both(zh: "在 macOS 和 Linux 上，在 Claude Code 启动的后台进程前面放一个企业启动器命令。Claude Code 会把自己的命令行追加到启动器后面运行，所以启动器必须 exec 进入 Claude Code；见「在企业启动器后面运行 Claude Code」…", en: "On macOS and Linux, place a corporate launcher command in front of the background processes Claude Code starts. Claude Code runs the launcher with its own command line appended, so the launcher must exec into Claude Code; see Run Claude Code behind a corporate launcher for the…")
					),
					textField(
						"teammateMode", .both(zh: "teammateMode", en: "teammateMode"), "",
						.both(zh: "选择 Claude Code 在哪里显示 agent team 的队友：你的主终端窗格内，还是终端支持时的分屏。见「选择显示模式」。", en: "Choose where Claude Code shows agent team teammates: inside your main terminal pane, or in split panes when your terminal supports them. See Choose a display mode.")
					),
					jsonField(
						"worktree", .both(zh: "worktree", en: "worktree"),
						.both(zh: "配置 Claude Code 如何为 --worktree、EnterWorktree 工具以及隔离的 subagent 和后台 session 创建和管理 git worktree。", en: "Configure how Claude Code creates and manages git worktrees for --worktree, the EnterWorktree tool, and isolated subagents and background sessions.")
					),
					textField(
						"worktree.baseRef", .both(zh: "worktree.baseRef", en: "worktree.baseRef"), "",
						.both(zh: "选择新 worktree 从哪个 ref 分叉。'fresh' 从 origin/<默认分支> 分叉，得到与远端一致的干净工作树；'head' 从你当前的本地 HEAD 分叉，因此未推送的提交和功能分支状态都会出现在 worktree 里。", en: "Choose which ref new worktrees branch from. 'fresh' branches from origin/<default-branch> for a clean tree matching the remote; 'head' branches from your current local HEAD, so unpushed commits and feature-branch state are present in the worktree.")
					),
					textField(
						"worktree.bgIsolation", .both(zh: "worktree.bgIsolation", en: "worktree.bgIsolation"), "",
						.both(zh: "选择后台 session 如何隔离它们的文件修改。取值为 'worktree' 时，Claude Code 在 session 调用 EnterWorktree 之前阻止在主检出里使用 Edit 和 Write；取值为 'none' 时，后台任务直接修改工作副本。对于 git worktree…的仓库，设为 'none'。", en: "Choose how background sessions isolate their file edits. With 'worktree', Claude Code blocks Edit and Write in the main checkout until the session calls EnterWorktree; with 'none', background jobs edit the working copy directly. Set 'none' for a repository where git worktrees…")
					),
					listField(
						"worktree.sparsePaths", .both(zh: "worktree.sparsePaths", en: "worktree.sparsePaths"),
						.both(zh: "通过 git sparse-checkout 只检出每个 worktree 里列出的目录。Claude Code 只把这些目录和根级文件写到磁盘，在大型 monorepo 里更快；见「只检出你需要的目录」。", en: "Check out only the listed directories in each worktree through git sparse-checkout. Claude Code writes only those directories plus root-level files to disk, which is faster in large monorepos; see Check out only the directories you need.")
					),
					listField(
						"worktree.symlinkDirectories", .both(zh: "worktree.symlinkDirectories", en: "worktree.symlinkDirectories"),
						.both(zh: "把主仓库里的目录软链到每个 worktree，这样就不必在磁盘上重复占用大目录。", en: "Symlink directories from the main repository into each worktree so you don't duplicate large directories on disk.")
					),
				]
			),
			SettingsSection(
				id: "claude-mcp",
				title: .both(zh: "MCP", en: "MCP"),
				icon: "point.3.connected.trianglepath.dotted",
				fields: [
					listField(
						"allowedMcpServers", .both(zh: "allowedMcpServers", en: "allowedMcpServers"),
						.both(zh: "允许人们添加哪些 MCP server 的允许列表。任何不匹配条目的 server，无论定义在哪里都会被 Claude Code 阻止，包括 plugin server、用 --mcp-config 传入的 server，以及来自 claude.ai 的 server。内置 server，例如 Claude in Chrome、ide server…", en: "Allowlist the MCP servers people can add. Claude Code blocks any server that doesn't match an entry wherever it's defined, including plugin servers, servers passed with --mcp-config, and servers from claude.ai. Built-in servers such as Claude in Chrome, the ide server Claude…")
					),
					listField(
						"deniedMcpServers", .both(zh: "deniedMcpServers", en: "deniedMcpServers"),
						.both(zh: "阻止特定的 MCP server。匹配的 server 无论定义在哪里，Claude Code 都拒绝加载，包括 plugin server、用 --mcp-config 传入的 server、来自 managed-mcp.json 的 server、来自 managedMcpServers 的 server，以及它自己去拉取的 claude.ai 连接器。进程内…", en: "Block specific MCP servers. Claude Code refuses to load a matching server wherever it's defined, including plugin servers, servers passed with --mcp-config, servers from managed-mcp.json, servers from managedMcpServers, and the claude.ai connectors it fetches itself. In-process…")
					),
					boolField(
						"disableClaudeAiConnectors", .both(zh: "disableClaudeAiConnectors", en: "disableClaudeAiConnectors"), fallback: false,
						.both(zh: "关闭 Claude Code 自己去拉取的 claude.ai MCP 连接器，使它既不拉取也不连接它们。任何设置文件里的 true 都会生效：仓库里签入的项目 .claude/settings.json 可以让这个仓库退出这些连接器，但项目级的 false 无法覆盖…", en: "Turn off the claude.ai MCP connectors Claude Code fetches itself, so it neither fetches nor connects them. A true in any settings file applies: a checked-in project .claude/settings.json can opt a repository out of those connectors, but a project-level false can't override a…")
					),
					listField(
						"disabledMcpjsonServers", .both(zh: "disabledMcpjsonServers", en: "disabledMcpjsonServers"),
						.both(zh: "拒绝项目 .mcp.json 文件里定义的特定 server，使 Claude Code 永不连接它们、也不请求你批准。任何设置文件里的拒绝都会生效，包括签入仓库的项目 .claude/settings.json。", en: "Reject specific servers defined in a project's .mcp.json file so Claude Code never connects them or asks you to approve them. A rejection in any settings file applies, including a project .claude/settings.json checked into the repository.")
					),
					boolField(
						"enableAllProjectMcpServers", .both(zh: "enableAllProjectMcpServers", en: "enableAllProjectMcpServers"), fallback: false,
						.both(zh: "不提示就批准项目 .mcp.json 文件里定义的所有 MCP server。当你在批准对话框里选择批准全部 server 时，Claude Code 会把这个键写入 .claude/settings.local.json。", en: "Approve every MCP server defined in project .mcp.json files without a prompt. Claude Code writes this key to .claude/settings.local.json when you choose to approve all servers in the approval dialog.")
					),
					listField(
						"enabledMcpjsonServers", .both(zh: "enabledMcpjsonServers", en: "enabledMcpjsonServers"),
						.both(zh: "批准项目 .mcp.json 文件里定义的特定 server，使 Claude Code 不经询问就连接它们。当你在批准对话框里批准某个 server 时，Claude Code 会把这个键写入 .claude/settings.local.json。", en: "Approve specific servers defined in project .mcp.json files so Claude Code connects them without asking. Claude Code writes this key to .claude/settings.local.json when you approve a server in the approval dialog.")
					),
				]
			),
			SettingsSection(
				id: "claude-plugins-and-skills",
				title: .both(zh: "插件与 Skills", en: "Plugins and skills"),
				icon: "puzzlepiece.extension",
				fields: [
					boolField(
						"disableBundledSkills", .both(zh: "disableBundledSkills", en: "disableBundledSkills"), fallback: false,
						.both(zh: "关闭 Claude Code 随附的 skills 和 workflow。Claude Code 会完全移除随附的 skills 和 workflow，而 /init 这类内置命令仍然可以输入，只是对模型隐藏。", en: "Turn off the skills and workflows included with Claude Code. Claude Code removes bundled skills and workflows entirely, while built-in commands such as /init stay typable but are hidden from the model.")
					),
					boolField(
						"disableSkillShellExecution", .both(zh: "disableSkillShellExecution", en: "disableSkillShellExecution"), fallback: false,
						.both(zh: "关闭来自用户、项目、plugin 或额外目录来源的 skills 与自定义命令里 !... 和 ! 块的内联 shell 执行。Claude Code 会把每条命令替换为 [shell command execution disabled by policy]，而不是运行它。", en: "Turn off inline shell execution for !... and ! blocks in skills and custom commands from user, project, plugin, or additional-directory sources. Claude Code replaces each command with [shell command execution disabled by policy]` instead of running it.")
					),
					jsonField(
						"enabledPlugins", .both(zh: "enabledPlugins", en: "enabledPlugins"),
						.both(zh: "按 plugin-name@marketplace-name 为键单独开关 plugin。在任何作用域都没有条目的 plugin 会回落到它的 defaultEnabled 值。当你用 /plugin 或 claude plugin enable 启用或禁用某个 plugin 时，Claude Code 会替你写这个键。", en: "Turn individual plugins on or off, keyed by plugin-name@marketplace-name. A plugin with no entry at any scope falls back to its defaultEnabled value. When you enable or disable a plugin with /plugin or claude plugin enable, Claude Code writes this key for you.")
					),
					jsonField(
						"extraKnownMarketplaces", .both(zh: "extraKnownMarketplaces", en: "extraKnownMarketplaces"),
						.both(zh: "按名称注册额外的 plugin 市场，这样打开这个仓库的人、或你的 managed settings 覆盖到的所有人，都不必自己添加就能得到该市场。Claude Code 会注册每个它还不认识的市场。某个 plugin 是否…", en: "Register additional plugin marketplaces by name, so that people who open the repository, or everyone your managed settings reach, get the marketplace without adding it themselves. Claude Code registers each marketplace it doesn't already know. Whether a plugin that…")
					),
					listField(
						"pluginConfigs", .both(zh: "pluginConfigs", en: "pluginConfigs"),
						.both(zh: "保存你在 plugin 的 userConfig 配置对话框里给出的非敏感答案，以 plugin ID 为键。你在对话框里填写时，Claude Code 会把这个键写入你的用户设置，所以不必手动编辑它。Claude Code 把敏感选项存储在 macOS…", en: "Store the non-sensitive answers you give a plugin's userConfig configuration dialog, keyed by plugin ID. Claude Code writes this key to your user settings when you fill in the dialog, so you don't need to edit it by hand. Claude Code stores sensitive options in the macOS…")
					),
					jsonField(
						"skillOverrides", .both(zh: "skillOverrides", en: "skillOverrides"),
						.both(zh: "不编辑 skill 的 SKILL.md 就隐藏或折叠它。Claude Code 会把每个 skill 名称下的值应用到它看到的 skill 列表和你的 / 自动补全上。", en: "Hide or collapse a skill without editing its SKILL.md. Claude Code applies the value under each skill's name to the skill list Claude sees and to your / autocomplete.")
					),
					boolField(
						"syncClaudeAiPlugins", .both(zh: "syncClaudeAiPlugins", en: "syncClaudeAiPlugins"), fallback: false,
						.both(zh: "关闭为你的 claude.ai 账号启用的 plugin 的下载。在你用 claude.ai 账号登录的终端 session 和 Cowork session 开始时，Claude Code 会把它们下载到 ~/.claude/plugins/synced/，并把每个都作为 <name>@synced 加载。设…", en: "Turn off the download of the plugins enabled for your claude.ai account. Claude Code downloads them into ~/.claude/plugins/synced/ at the start of terminal sessions where you sign in with your claude.ai account and in Cowork sessions, and loads each one as <name>@synced. Set…")
					),
					boolField(
						"syncClaudeAiSkills", .both(zh: "syncClaudeAiSkills", en: "syncClaudeAiSkills"), fallback: false,
						.both(zh: "关闭为你的 claude.ai 账号启用的 skills 的下载。在你用 claude.ai 账号登录的终端 session（交互式或非交互式）以及 Cowork 和 cloud session 里，Claude Code 会把它们下载到 ~/.claude/skills/synced/。设 false…", en: "Turn off the download of the skills enabled for your claude.ai account. Claude Code downloads them into ~/.claude/skills/synced/ in terminal sessions where you sign in with your claude.ai account, interactive or non-interactive, and in Cowork and cloud sessions. Set false to…")
					),
				]
			),
			SettingsSection(
				id: "claude-hooks-and-automation",
				title: .both(zh: "Hooks 与自动化", en: "Hooks and automation"),
				icon: "bolt",
				fields: [
					listField(
						"allowedHttpHookUrls", .both(zh: "allowedHttpHookUrls", en: "allowedHttpHookUrls"),
						.both(zh: "限制 HTTP hook 可以访问哪些 URL。当你定义了这个键，只有当 HTTP hook 的 URL 匹配其中一个模式时 Claude Code 才运行它，其余的一律阻止、不运行；空数组会阻止所有 HTTP hook。", en: "Limit which URLs HTTP hooks can target. When you define this key, Claude Code runs an HTTP hook only if its URL matches one of the patterns and blocks the rest without running them; an empty array blocks every HTTP hook.")
					),
					boolField(
						"disableAllHooks", .both(zh: "disableAllHooks", en: "disableAllHooks"), fallback: false,
						.both(zh: "关闭 hook、任何自定义状态栏，以及任何自定义文件建议命令。用它临时关掉这一切，而不必从设置里删除它们。", en: "Turn off hooks, any custom status line, and any custom file suggestion command. Use it to turn all of these off temporarily without deleting them from your settings.")
					),
					boolField(
						"disableWorkflows", .both(zh: "disableWorkflows", en: "disableWorkflows"), fallback: false,
						.both(zh: "为你的设置覆盖到的所有人关闭动态 workflow 和随附的 workflow 命令，例如组织通过 managed settings 下发。如果你只想为自己开关 workflow，请改用 enableWorkflows，/config 里的 **Dynamic workflows** 开关写的就是这个键…", en: "Turn off dynamic workflows and the bundled workflow commands for everyone your settings reach, such as an organization through managed settings. To turn workflows on or off just for yourself, use enableWorkflows instead, which the **Dynamic workflows** toggle in /config writes…")
					),
					boolField(
						"enableWorkflows", .both(zh: "enableWorkflows", en: "enableWorkflows"), fallback: false,
						.both(zh: "当你所在套餐的默认值不合意时，为自己开关动态 workflow。它在 /config 里显示为 **Dynamic workflows**，开启时把这个键写入你的用户设置，切回套餐默认时再移除它。要为其它人关闭 workflow…", en: "Turn dynamic workflows on or off for yourself when your plan's default isn't what you want. Appears in /config as **Dynamic workflows**, which writes this key to your user settings and removes it again when you toggle back to your plan's default. To turn workflows off for…")
					),
					listField(
						"hooks", .both(zh: "hooks", en: "hooks"),
						.both(zh: "在 Claude Code 生命周期的各个节点（例如工具调用之前、session 启动时）把你自己的命令、prompt、agent、HTTP 请求或 MCP 工具作为 hook 运行；hooks 参考列出了每个事件、它的负载和退出码。每个事件映射到一个 matcher…", en: "Run your own commands, prompts, agents, HTTP requests, or MCP tools as hooks at points in Claude Code's lifecycle, such as before a tool call or when a session starts; the hooks reference lists every event, its payload, and its exit codes. Each event maps to a list of matcher…")
					),
					listField(
						"httpHookAllowedEnvVars", .both(zh: "httpHookAllowedEnvVars", en: "httpHookAllowedEnvVars"),
						.both(zh: "HTTP hook 可以把环境变量的值放进请求头，例如 Authorization: Bearer $HOOK_TOKEN 头，但只能用于该 hook 在自己的 allowedEnvVars 里列出的变量。这个键为所有 HTTP hook 给那份列表设一个外层上限：hook 可以…", en: "An HTTP hook can put the value of an environment variable into a request header, for example an Authorization: Bearer $HOOK_TOKEN header, but only for variables the hook lists in its own allowedEnvVars. This key sets an outer limit on that list for every HTTP hook: a hook can…")
					),
					boolField(
						"workflowKeywordTriggerEnabled", .both(zh: "workflowKeywordTriggerEnabled", en: "workflowKeywordTriggerEnabled"), fallback: true,
						.both(zh: "选择在 prompt 里输入关键词 ultracode 是否触发动态 workflow。设为 false 可以只是打出这个词而不触发。", en: "Choose whether typing the keyword ultracode in a prompt triggers a dynamic workflow. Set it to false to type the word without triggering one.")
					),
					textField(
						"workflowSizeGuideline", .both(zh: "workflowSizeGuideline", en: "workflowSizeGuideline"), "",
						.both(zh: "设置 Claude 在它编写的动态 workflow 里瞄准的 agent 数量。Claude Code 把这个值作为建议而不是强制上限发给 Claude：'small' 要求少于 5 个 agent，'medium' 少于 10 个，'large' 少于 50。当你想约束一个…时选 'small'。", en: "Set the agent count Claude aims for in the dynamic workflows it writes. Claude Code sends the value to Claude as advice, not an enforced cap: 'small' asks for fewer than 5 agents, 'medium' fewer than 10, and 'large' fewer than 50. Choose 'small' when you want to bound what a…")
					),
				]
			),
			SettingsSection(
				id: "claude-remote-desktop-and-notifications",
				title: .both(zh: "远程、桌面与通知", en: "Remote, desktop, and notifications"),
				icon: "bell",
				fields: [
					boolField(
						"agentPushNotifEnabled", .both(zh: "agentPushNotifEnabled", en: "agentPushNotifEnabled"), fallback: false,
						.both(zh: "允许 Claude 在它认为值得时给你的手机发推送通知，例如一个长任务完成时。Claude Code 会把这个选择同步到你的账号，推送在 Remote Control 连接期间到达。在 /config 里显示为 **Push when Claude…**。", en: "Allow Claude to send a push notification to your phone when it decides one is worth sending, for example when a long task finishes. Claude Code syncs this choice to your account, and pushes arrive while Remote Control is connected. Appears in /config as **Push when Claude…")
					),
					boolField(
						"awaySummaryEnabled", .both(zh: "awaySummaryEnabled", en: "awaySummaryEnabled"), fallback: false,
						.both(zh: "当你离开几分钟后回到终端时，显示一行 session 回顾。设为 false，或在 /config 里关掉 **Session recap**，即可停止回顾。", en: "Show a one-line session recap when you return to the terminal after a few minutes away. Set it to false, or turn off **Session recap** in /config, to stop the recap.")
					),
					boolField(
						"disableArtifact", .both(zh: "disableArtifact", en: "disableArtifact"), fallback: false,
						.both(zh: "<Warning> 已废弃，由 enableArtifact 取代。Claude Code 仍把 disableArtifact: true 视为等价于 enableArtifact: false，并忽略 disableArtifact: false。</Warning> 请改用 enableArtifact 关闭 Artifact 工具，该工具把 session 输出发布为…", en: "<Warning> Deprecated, and replaced by enableArtifact. Claude Code still honors disableArtifact: true as equivalent to enableArtifact: false, and ignores disableArtifact: false. </Warning> Use enableArtifact instead to turn off the Artifact tool, which publishes session output as…")
					),
					textField(
						"disableDeepLinkRegistration", .both(zh: "disableDeepLinkRegistration", en: "disableDeepLinkRegistration"), "",
						.both(zh: "阻止 Claude Code 向操作系统注册 claude-cli:// 协议处理器，否则它会在你发出交互式 session 的第一条 prompt 后注册。深链接让外部工具能带着预填 prompt 打开 Claude Code session。在…里设置它。", en: "Stop Claude Code from registering the claude-cli:// protocol handler with the operating system, which it otherwise does after you send the first prompt of an interactive session. Deep links let external tools open a Claude Code session with a pre-filled prompt. Set this in…")
					),
					boolField(
						"disableRemoteControl", .both(zh: "disableRemoteControl", en: "disableRemoteControl"), fallback: false,
						.both(zh: "关闭 Remote Control：Claude Code 随后会拒绝 claude remote-control、--remote-control 标志、自动启动和 session 内开关，并报告你的组织策略已禁用它。在 managed settings 里设置它，以便按设备做 MDM 强制。", en: "Turn off Remote Control: Claude Code then refuses claude remote-control, the --remote-control flag, auto-start, and the in-session toggle, and reports that your organization's policy disabled it. Place it in managed settings for per-device MDM enforcement.")
					),
					boolField(
						"enableArtifact", .both(zh: "enableArtifact", en: "enableArtifact"), fallback: false,
						.both(zh: "关闭 Artifact 工具，该工具把 session 输出发布为 claude.ai 上的私有网页。当你在 /config 里关掉 **Artifacts** 一行时，Claude Code 会把这个键写入你的用户设置，所以通常不必手动编辑它。需要 Claude Code v2.1.196 或更高版本。", en: "Turn off the Artifact tool, which publishes session output as a private web page on claude.ai. When you turn the **Artifacts** row off in /config, Claude Code writes this key to your user settings, so you don't usually edit it by hand. Requires Claude Code v2.1.196 or later.")
					),
					boolField(
						"inputNeededNotifEnabled", .both(zh: "inputNeededNotifEnabled", en: "inputNeededNotifEnabled"), fallback: false,
						.both(zh: "当有权限提示或问题在等待你输入时，在你的手机上收到推送通知。Claude Code 只在 Remote Control 连接期间发送这些通知。在 /config 里显示为 **Push when actions required**。", en: "Get a push notification on your phone when a permission prompt or question is waiting for your input. Claude Code sends these only while Remote Control is connected. Appears in /config as **Push when actions required**.")
					),
					textField(
						"preferredNotifChannel", .both(zh: "preferredNotifChannel", en: "preferredNotifChannel"), "",
						.both(zh: "选择任务完成或有权限提示在等待时，Claude Code 如何通知你。在 /config 里显示为 **Local notifications**。", en: "Choose how Claude Code notifies you when a task completes or a permission prompt is waiting. Appears in /config as **Local notifications**.")
					),
					textField(
						"remote.defaultEnvironmentId", .both(zh: "remote.defaultEnvironmentId", en: "remote.defaultEnvironmentId"), "",
						.both(zh: "为你在 CLI 里创建的 cloud session（例如用 claude --cloud）挑选默认 cloud 环境。当你用 /remote-env 选择环境时，Claude Code 会把这个键写入你的用户设置。", en: "Pick the default cloud environment for cloud sessions you create from the CLI, such as with claude --cloud. Claude Code writes this key to your user settings when you pick an environment with /remote-env.")
					),
					boolField(
						"remoteControlAtStartup", .both(zh: "remoteControlAtStartup", en: "remoteControlAtStartup"), fallback: false,
						.both(zh: "每个交互式 session 启动时自动连接 Remote Control，而不是等待 /remote-control。设为 true 开启自动连接，设为 false 关闭。在 /config 里显示为 **Enable Remote Control for all sessions**。", en: "Connect Remote Control automatically when each interactive session starts, instead of waiting for /remote-control. Set it to true to turn auto-connect on, false to turn it off. Appears in /config as **Enable Remote Control for all sessions**.")
					),
					listField(
						"sshConfigs", .both(zh: "sshConfigs", en: "sshConfigs"),
						.both(zh: "把 SSH 连接加入 Desktop 环境下拉列表。管理员用它给团队分发共享连接。你在 managed settings 里定义的连接会显示为 managed，用户可以选择它们，但不能在应用里编辑或删除。", en: "Add SSH connections to the Desktop environment dropdown. Administrators use it to distribute shared connections to a team. Connections you define in managed settings show as managed, so users can select them but can't edit or delete them in the app.")
					),
				]
			),
		]
	)
}
