// Generated by Tools/make-claude-schema.py from the upstream settings
// reference. Do not edit by hand; re-run the script after an upgrade.

import Foundation

extension SettingsSchema {
	public static let claudeCode = SettingsSchemaDefinition(
		id: "claude-code",
		title: "Claude Code 设置",
		sections: [
			SettingsSection(
				id: "claude-model-and-responses",
				title: "模型与回复",
				icon: "cpu",
				fields: [
					textField("advisorModel", "advisorModel", "", "Pick which model answers when Claude calls the server-side advisor tool. Unset it to turn the advisor off. The advisor must be at least as capable as your main model. See Choose an advisor model for the accepted pairings and what happens when you pick one that isn't accepted…"),
					boolField("alwaysThinkingEnabled", "alwaysThinkingEnabled", fallback: false, "Turn extended thinking off for every session by setting this to false. Thinking is on by default, so true changes nothing. Most people set this through /config rather than by editing the file. On models that always think, such as Opus 5.5, Sonnet 5.5, and the Fable models, false…"),
					listField("availableModels", "availableModels", "Restrict which models people can select for the main session, subagents, skills, and the advisor. A managed list constrains /model, --model, and the model key in a developer's own files; a model outside it can't be selected. With the default prefix matching, this doesn't touch…"),
					textField("effortLevel", "effortLevel", "", "Set a default effort level for models you haven't saved a level for. Lower levels are faster and cheaper on straightforward tasks, and higher levels reason more deeply on complex problems. When you run /effort low, medium, high, or xhigh in an interactive session on your…"),
					boolField("enforceAvailableModels", "enforceAvailableModels", fallback: false, "The /model picker has a **Default** option, and default model setting describes the model it resolves to. An availableModels allowlist limits the models you can name, but with the default prefix matching it doesn't remap your account type's default, so **Default** can still…"),
					listField("fallbackModel", "fallbackModel", "Name backup models for Claude Code to try, in order, when your primary model is overloaded or unavailable. Claude Code switches to the next available model in the chain for the rest of the turn and shows a notice. Without a chain, Claude Code retries the same model and then…"),
					boolField("fastMode", "fastMode", fallback: false, "Turn fast mode on for sessions where it's available, for interactive work like rapid iteration or live debugging where you want speed at a higher cost per token. You don't usually edit this key by hand: running /fast writes fastMode: true to ~/.claude/settings.json, and running…"),
					boolField("fastModePerSessionOptIn", "fastModePerSessionOptIn", fallback: false, "Normally, running /fast saves fastMode to a person's user settings, so fast mode is on at the start of every later session. Set this key to true to stop that: a saved fastMode: true no longer turns fast mode on at session start, and each person has to run /fast in each session…"),
					textField("language", "language", "", "Have Claude respond in a language other than English by default. There is no fixed list for responses: Claude Code passes the value verbatim to Claude as an instruction to always respond in that language, so any language name Claude can read works. Claude Code doesn't check the…"),
					textField("maxEffortLevel", "maxEffortLevel", "", "Cap the effort level a session can use, leaving lower levels available. Any higher level runs at the cap instead, including one from /effort, the /model picker, --effort, CLAUDE_CODE_EFFORT_LEVEL, a skill's or subagent's effort frontmatter, or the model's own default. Claude…"),
					textField("model", "model", "", "Set the model every new session uses, so you don't have to pick one with /model each time. Setting it here doesn't stop you from switching mid-session. If your admin set an organization default model to override user selection, you get that model even when you set this key in…"),
					jsonField("modelOverrides", "modelOverrides", "Map Anthropic model IDs to provider-specific model IDs, such as Amazon Bedrock inference profile ARNs. Each model picker entry then uses its mapped value when calling the provider API. Administrators use this on Amazon Bedrock, Google Cloud's Agent Platform, and Microsoft…"),
					listField("modelPicker", "modelPicker", "List the models the /model picker offers, in the order you write them and under labels you choose, so the picker lists the models your organization runs, after the built-in lineup or instead of it. Each row's model is taken verbatim, so it accepts anything --model accepts: an…"),
					jsonField("modelSettings", "modelSettings", "Save an effort level for each model you use. Requires Claude Code v2.1.251 or later. In an interactive session on your machine, when you save low, medium, high, or xhigh as your default with /effort or the /model picker's effort slider, Claude Code writes that level here under…"),
					textField("outputStyle", "outputStyle", "", "Select an output style by name. An output style is a saved set of instructions that changes Claude's role, tone, and output format, such as the built-in Explanatory and Learning styles or one you wrote yourself. If you change this key during a session, Claude uses the new style…"),
					textField("promptCacheTtl", "promptCacheTtl", "", "Choose how long the prompt cache holds the main conversation. This key applies to your interactive, -p, and Agent SDK turns, together with the helpers Claude Code runs inline with them. The one-hour lifetime keeps the cache warm across longer breaks, and the API bills each cache…"),
					boolField("showThinkingSummaries", "showThinkingSummaries", fallback: false, "See summaries of Claude's extended thinking in interactive sessions. Set it if you want the full summaries when you expand thinking with Ctrl+O. When unset or false, the Anthropic API redacts thinking blocks and Claude Code shows a collapsed stub; third-party providers don't…"),
					textField("subagentPromptCacheTtl", "subagentPromptCacheTtl", "", "Choose how long the prompt cache holds the requests Claude Code makes outside the main conversation. This key applies to subagents, workflows, and Claude Code's own background and helper requests, such as compaction and session titles. The one-hour lifetime keeps the cache warm…"),
					boolField("switchModelsOnFlag", "switchModelsOnFlag", fallback: true, "Choose what happens when a safety classifier flags a request: switch to the fallback model and continue, or pause so you can choose between switching and editing the prompt."),
					boolField("ultracode", "ultracode", fallback: false, "Start sessions with ultracode on. With it on, Claude plans a workflow for each substantive task instead of waiting for you to ask. Claude plans workflows only when dynamic workflows are enabled for you and your model supports xhigh effort. The key doesn't change the session's…"),
				]
			),
			SettingsSection(
				id: "claude-permission-settings",
				title: "权限",
				icon: "lock.shield",
				fields: [
					jsonField("autoMode", "autoMode", "Add your own rules to what the auto mode classifier blocks and allows. Use it to tell the classifier which repos, buckets, and domains your organization trusts, so it stops blocking routine internal operations. The classifier ships with built-in allow and deny rules. Include the…"),
					boolField("autoMode.classifyAllShell", "autoMode.classifyAllShell", fallback: false, "Send every Bash and PowerShell command through the auto mode classifier while auto mode is active. By default, auto mode suspends only allow rules that could run arbitrary code: tool-wide and wildcard rules such as Bash(*), and interpreter or shell-wrapper prefixes such as…"),
					textField("disableAutoMode", "disableAutoMode", "", "Remove auto mode from the Shift+Tab cycle. Any session that would otherwise start in auto mode, whether from --permission-mode auto, a settings file, or the built-in default, starts in default instead. Administrators set it in managed settings to prevent developers in their…"),
					jsonField("permissions", "permissions", "Control which tools Claude can use without asking, which ones always prompt, and which ones are blocked, and set the permission mode a session starts in. Every permissions.* key below nests under this object."),
					listField("permissions.additionalDirectories", "permissions.additionalDirectories", "Give Claude file access to directories outside the one you started in, as additional working directories. Most .claude/ configuration is not discovered from these directories."),
					listField("permissions.allow", "permissions.allow", "List the tool uses Claude Code approves without asking you. In an MCP rule, * can appear only in the tool name after the mcp__<server>__ prefix, such as mcp__github__get_*; it can't appear in the server name."),
					listField("permissions.ask", "permissions.ask", "List the tool uses that prompt you for confirmation even in a permission mode that would otherwise approve them, such as acceptEdits or bypassPermissions. In dontAsk mode Claude Code denies a matching tool use instead of prompting."),
					boolField("permissions.blockReadsOutsideWorkingDirectories", "permissions.blockReadsOutsideWorkingDirectories", fallback: false, "Stop Claude from reading paths outside the session's working directories with the Read, Grep, Glob, and LSP tools, in every permission mode including bypassPermissions. A Bash command that reads a matching path through a file command Claude Code recognizes, such as cat, prompts…"),
					textField("permissions.defaultMode", "permissions.defaultMode", "", "Set the permission mode new sessions start in. When you leave it unset, sessions start in the built-in default for your surface."),
					listField("permissions.deny", "permissions.deny", "List the tool uses Claude Code blocks. Use it for files that hold API keys, secrets, or environment values: Claude Code excludes matching files from file discovery and search results, denies reads of them, and blocks the Edit and Write tools on the matching paths. Read and Edit…"),
					textField("permissions.disableBypassPermissionsMode", "permissions.disableBypassPermissionsMode", "", "Prevent anyone from entering bypassPermissions mode. Claude Code then rejects the --dangerously-skip-permissions flag, and ignores an agent definition's permissionMode: bypassPermissions, so the subagent runs with the parent session's permission mode."),
					boolField("skipAutoPermissionPrompt", "skipAutoPermissionPrompt", fallback: false, "Skip the one-time notice describing auto mode that Claude Code shows when you first enter auto mode yourself, for example through your own settings or the mode selector, rather than when the built-in default starts a session in it. Claude Code shows that notice once and then…"),
					boolField("skipDangerousModePermissionPrompt", "skipDangerousModePermissionPrompt", fallback: false, "Skip the confirmation dialog Claude Code shows before a session enters bypassPermissions mode, whether from --dangerously-skip-permissions or from defaultMode: 'bypassPermissions'. Claude Code writes true here in your user settings when you accept that dialog once."),
					boolField("useAutoModeDuringPlan", "useAutoModeDuringPlan", fallback: true, "Choose whether Claude Code uses the auto mode classifier to review shell commands in plan mode. With the default true, the classifier reviews each command during planning when auto mode is available and you see no prompt, except for critical-path removals. Set false to get a…"),
				]
			),
			SettingsSection(
				id: "claude-agents-sessions-and-worktrees",
				title: "Agent 与会话",
				icon: "person.2",
				fields: [
					textField("agent", "agent", "", "Run the main thread as a named subagent, so Claude Code applies that subagent's system prompt, tool restrictions, and model to your session. The same key sets the default agent for sessions you dispatch from claude agents."),
					textField("crossSessionInbound", "crossSessionInbound", "", "Choose what this session does with messages arriving from your other Claude Code sessions. When no value applies, Claude Code decides per message from the two sessions' permission-mode classes. Requires Claude Code v2.1.224 or later."),
					boolField("disableAgentView", "disableAgentView", fallback: false, "Turn off background agents and agent view: claude agents, --bg, /background, and the on-demand supervisor. Set it in managed settings to enforce it for an organization."),
					boolField("isolatePeerMachines", "isolatePeerMachines", fallback: false, "Require your explicit approval before Claude's SendMessage reaches one of your sessions beyond this machine; see Require approval for cross-machine messages. The approval prompt appears even in bypassPermissions mode."),
					textField("processWrapper", "processWrapper", "", "On macOS and Linux, place a corporate launcher command in front of the background processes Claude Code starts. Claude Code runs the launcher with its own command line appended, so the launcher must exec into Claude Code; see Run Claude Code behind a corporate launcher for the…"),
					textField("teammateMode", "teammateMode", "", "Choose where Claude Code shows agent team teammates: inside your main terminal pane, or in split panes when your terminal supports them. See Choose a display mode."),
					jsonField("worktree", "worktree", "Configure how Claude Code creates and manages git worktrees for --worktree, the EnterWorktree tool, and isolated subagents and background sessions."),
					textField("worktree.baseRef", "worktree.baseRef", "", "Choose which ref new worktrees branch from. 'fresh' branches from origin/<default-branch> for a clean tree matching the remote; 'head' branches from your current local HEAD, so unpushed commits and feature-branch state are present in the worktree."),
					textField("worktree.bgIsolation", "worktree.bgIsolation", "", "Choose how background sessions isolate their file edits. With 'worktree', Claude Code blocks Edit and Write in the main checkout until the session calls EnterWorktree; with 'none', background jobs edit the working copy directly. Set 'none' for a repository where git worktrees…"),
					listField("worktree.sparsePaths", "worktree.sparsePaths", "Check out only the listed directories in each worktree through git sparse-checkout. Claude Code writes only those directories plus root-level files to disk, which is faster in large monorepos; see Check out only the directories you need."),
					listField("worktree.symlinkDirectories", "worktree.symlinkDirectories", "Symlink directories from the main repository into each worktree so you don't duplicate large directories on disk."),
				]
			),
			SettingsSection(
				id: "claude-mcp",
				title: "MCP",
				icon: "point.3.connected.trianglepath.dotted",
				fields: [
					listField("allowedMcpServers", "allowedMcpServers", "Allowlist the MCP servers people can add. Claude Code blocks any server that doesn't match an entry wherever it's defined, including plugin servers, servers passed with --mcp-config, and servers from claude.ai. Built-in servers such as Claude in Chrome, the ide server Claude…"),
					listField("deniedMcpServers", "deniedMcpServers", "Block specific MCP servers. Claude Code refuses to load a matching server wherever it's defined, including plugin servers, servers passed with --mcp-config, servers from managed-mcp.json, servers from managedMcpServers, and the claude.ai connectors it fetches itself. In-process…"),
					boolField("disableClaudeAiConnectors", "disableClaudeAiConnectors", fallback: false, "Turn off the claude.ai MCP connectors Claude Code fetches itself, so it neither fetches nor connects them. A true in any settings file applies: a checked-in project .claude/settings.json can opt a repository out of those connectors, but a project-level false can't override a…"),
					listField("disabledMcpjsonServers", "disabledMcpjsonServers", "Reject specific servers defined in a project's .mcp.json file so Claude Code never connects them or asks you to approve them. A rejection in any settings file applies, including a project .claude/settings.json checked into the repository."),
					boolField("enableAllProjectMcpServers", "enableAllProjectMcpServers", fallback: false, "Approve every MCP server defined in project .mcp.json files without a prompt. Claude Code writes this key to .claude/settings.local.json when you choose to approve all servers in the approval dialog."),
					listField("enabledMcpjsonServers", "enabledMcpjsonServers", "Approve specific servers defined in project .mcp.json files so Claude Code connects them without asking. Claude Code writes this key to .claude/settings.local.json when you approve a server in the approval dialog."),
				]
			),
			SettingsSection(
				id: "claude-plugins-and-skills",
				title: "插件与 Skills",
				icon: "puzzlepiece.extension",
				fields: [
					boolField("disableBundledSkills", "disableBundledSkills", fallback: false, "Turn off the skills and workflows included with Claude Code. Claude Code removes bundled skills and workflows entirely, while built-in commands such as /init stay typable but are hidden from the model."),
					boolField("disableSkillShellExecution", "disableSkillShellExecution", fallback: false, "Turn off inline shell execution for !... and ! blocks in skills and custom commands from user, project, plugin, or additional-directory sources. Claude Code replaces each command with [shell command execution disabled by policy]` instead of running it."),
					jsonField("enabledPlugins", "enabledPlugins", "Turn individual plugins on or off, keyed by plugin-name@marketplace-name. A plugin with no entry at any scope falls back to its defaultEnabled value. When you enable or disable a plugin with /plugin or claude plugin enable, Claude Code writes this key for you."),
					jsonField("extraKnownMarketplaces", "extraKnownMarketplaces", "Register additional plugin marketplaces by name, so that people who open the repository, or everyone your managed settings reach, get the marketplace without adding it themselves. Claude Code registers each marketplace it doesn't already know. Whether a plugin that…"),
					listField("pluginConfigs", "pluginConfigs", "Store the non-sensitive answers you give a plugin's userConfig configuration dialog, keyed by plugin ID. Claude Code writes this key to your user settings when you fill in the dialog, so you don't need to edit it by hand. Claude Code stores sensitive options in the macOS…"),
					jsonField("skillOverrides", "skillOverrides", "Hide or collapse a skill without editing its SKILL.md. Claude Code applies the value under each skill's name to the skill list Claude sees and to your / autocomplete."),
					boolField("syncClaudeAiPlugins", "syncClaudeAiPlugins", fallback: false, "Turn off the download of the plugins enabled for your claude.ai account. Claude Code downloads them into ~/.claude/plugins/synced/ at the start of terminal sessions where you sign in with your claude.ai account and in Cowork sessions, and loads each one as <name>@synced. Set…"),
					boolField("syncClaudeAiSkills", "syncClaudeAiSkills", fallback: false, "Turn off the download of the skills enabled for your claude.ai account. Claude Code downloads them into ~/.claude/skills/synced/ in terminal sessions where you sign in with your claude.ai account, interactive or non-interactive, and in Cowork and cloud sessions. Set false to…"),
				]
			),
			SettingsSection(
				id: "claude-hooks-and-automation",
				title: "Hooks 与自动化",
				icon: "bolt",
				fields: [
					listField("allowedHttpHookUrls", "allowedHttpHookUrls", "Limit which URLs HTTP hooks can target. When you define this key, Claude Code runs an HTTP hook only if its URL matches one of the patterns and blocks the rest without running them; an empty array blocks every HTTP hook."),
					boolField("disableAllHooks", "disableAllHooks", fallback: false, "Turn off hooks, any custom status line, and any custom file suggestion command. Use it to turn all of these off temporarily without deleting them from your settings."),
					boolField("disableWorkflows", "disableWorkflows", fallback: false, "Turn off dynamic workflows and the bundled workflow commands for everyone your settings reach, such as an organization through managed settings. To turn workflows on or off just for yourself, use enableWorkflows instead, which the **Dynamic workflows** toggle in /config writes…"),
					boolField("enableWorkflows", "enableWorkflows", fallback: false, "Turn dynamic workflows on or off for yourself when your plan's default isn't what you want. Appears in /config as **Dynamic workflows**, which writes this key to your user settings and removes it again when you toggle back to your plan's default. To turn workflows off for…"),
					listField("hooks", "hooks", "Run your own commands, prompts, agents, HTTP requests, or MCP tools as hooks at points in Claude Code's lifecycle, such as before a tool call or when a session starts; the hooks reference lists every event, its payload, and its exit codes. Each event maps to a list of matcher…"),
					listField("httpHookAllowedEnvVars", "httpHookAllowedEnvVars", "An HTTP hook can put the value of an environment variable into a request header, for example an Authorization: Bearer $HOOK_TOKEN header, but only for variables the hook lists in its own allowedEnvVars. This key sets an outer limit on that list for every HTTP hook: a hook can…"),
					boolField("workflowKeywordTriggerEnabled", "workflowKeywordTriggerEnabled", fallback: true, "Choose whether typing the keyword ultracode in a prompt triggers a dynamic workflow. Set it to false to type the word without triggering one."),
					textField("workflowSizeGuideline", "workflowSizeGuideline", "", "Set the agent count Claude aims for in the dynamic workflows it writes. Claude Code sends the value to Claude as advice, not an enforced cap: 'small' asks for fewer than 5 agents, 'medium' fewer than 10, and 'large' fewer than 50. Choose 'small' when you want to bound what a…"),
				]
			),
			SettingsSection(
				id: "claude-remote-desktop-and-notifications",
				title: "远程、桌面与通知",
				icon: "bell",
				fields: [
					boolField("agentPushNotifEnabled", "agentPushNotifEnabled", fallback: false, "Allow Claude to send a push notification to your phone when it decides one is worth sending, for example when a long task finishes. Claude Code syncs this choice to your account, and pushes arrive while Remote Control is connected. Appears in /config as **Push when Claude…"),
					boolField("awaySummaryEnabled", "awaySummaryEnabled", fallback: false, "Show a one-line session recap when you return to the terminal after a few minutes away. Set it to false, or turn off **Session recap** in /config, to stop the recap."),
					boolField("disableArtifact", "disableArtifact", fallback: false, "<Warning> Deprecated, and replaced by enableArtifact. Claude Code still honors disableArtifact: true as equivalent to enableArtifact: false, and ignores disableArtifact: false. </Warning> Use enableArtifact instead to turn off the Artifact tool, which publishes session output as…"),
					textField("disableDeepLinkRegistration", "disableDeepLinkRegistration", "", "Stop Claude Code from registering the claude-cli:// protocol handler with the operating system, which it otherwise does after you send the first prompt of an interactive session. Deep links let external tools open a Claude Code session with a pre-filled prompt. Set this in…"),
					boolField("disableRemoteControl", "disableRemoteControl", fallback: false, "Turn off Remote Control: Claude Code then refuses claude remote-control, the --remote-control flag, auto-start, and the in-session toggle, and reports that your organization's policy disabled it. Place it in managed settings for per-device MDM enforcement."),
					boolField("enableArtifact", "enableArtifact", fallback: false, "Turn off the Artifact tool, which publishes session output as a private web page on claude.ai. When you turn the **Artifacts** row off in /config, Claude Code writes this key to your user settings, so you don't usually edit it by hand. Requires Claude Code v2.1.196 or later."),
					boolField("inputNeededNotifEnabled", "inputNeededNotifEnabled", fallback: false, "Get a push notification on your phone when a permission prompt or question is waiting for your input. Claude Code sends these only while Remote Control is connected. Appears in /config as **Push when actions required**."),
					textField("preferredNotifChannel", "preferredNotifChannel", "", "Choose how Claude Code notifies you when a task completes or a permission prompt is waiting. Appears in /config as **Local notifications**."),
					textField("remote.defaultEnvironmentId", "remote.defaultEnvironmentId", "", "Pick the default cloud environment for cloud sessions you create from the CLI, such as with claude --cloud. Claude Code writes this key to your user settings when you pick an environment with /remote-env."),
					boolField("remoteControlAtStartup", "remoteControlAtStartup", fallback: false, "Connect Remote Control automatically when each interactive session starts, instead of waiting for /remote-control. Set it to true to turn auto-connect on, false to turn it off. Appears in /config as **Enable Remote Control for all sessions**."),
					listField("sshConfigs", "sshConfigs", "Add SSH connections to the Desktop environment dropdown. Administrators use it to distribute shared connections to a team. Connections you define in managed settings show as managed, so users can select them but can't edit or delete them in the app."),
				]
			),
		]
	)
}
